CREATE TABLE `voucherBatches` (
	`id` int AUTO_INCREMENT NOT NULL,
	`organizationId` int NOT NULL,
	`templateId` int NOT NULL,
	`batchName` varchar(255) NOT NULL,
	`batchType` enum('manual','campaign','birthday','rfm_segment','all_customers') DEFAULT 'manual',
	`totalRecipients` int DEFAULT 0,
	`successCount` int DEFAULT 0,
	`failedCount` int DEFAULT 0,
	`status` enum('pending','processing','completed','failed','cancelled') DEFAULT 'pending',
	`targetCriteria` json,
	`scheduledAt` timestamp,
	`startedAt` timestamp,
	`completedAt` timestamp,
	`errorMessage` text,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `voucherBatches_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `voucherInstances` (
	`id` int AUTO_INCREMENT NOT NULL,
	`organizationId` int NOT NULL,
	`templateId` int NOT NULL,
	`customerId` int NOT NULL,
	`voucherCode` varchar(50) NOT NULL,
	`qrCodeUrl` text,
	`status` enum('active','used','expired','cancelled','transferred') DEFAULT 'active',
	`remainingUses` int DEFAULT 1,
	`usedCount` int DEFAULT 0,
	`validFrom` timestamp NOT NULL DEFAULT (now()),
	`validUntil` timestamp,
	`issuedBy` int,
	`issueReason` varchar(255),
	`issueChannel` enum('manual','campaign','birthday','referral','purchase','line') DEFAULT 'manual',
	`linePushStatus` enum('pending','sent','failed','not_applicable') DEFAULT 'pending',
	`linePushAt` timestamp,
	`linePushError` text,
	`originalOwnerId` int,
	`transferredAt` timestamp,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `voucherInstances_id` PRIMARY KEY(`id`),
	CONSTRAINT `voucherInstances_voucherCode_unique` UNIQUE(`voucherCode`)
);
--> statement-breakpoint
CREATE TABLE `voucherRedemptions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`organizationId` int NOT NULL,
	`voucherInstanceId` int NOT NULL,
	`customerId` int NOT NULL,
	`redemptionMethod` enum('qr_scan','manual_code','auto_apply') DEFAULT 'qr_scan',
	`redeemedBy` int,
	`orderId` int,
	`appointmentId` int,
	`treatmentRecordId` int,
	`discountApplied` decimal(10,2),
	`originalAmount` decimal(10,2),
	`finalAmount` decimal(10,2),
	`redemptionLocation` varchar(255),
	`notes` text,
	`redeemedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `voucherRedemptions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `voucherTemplates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`organizationId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`type` enum('treatment','discount','gift_card','stored_value','free_item') DEFAULT 'treatment',
	`value` decimal(10,2),
	`valueType` enum('fixed_amount','percentage','treatment_count') DEFAULT 'fixed_amount',
	`applicableProducts` json,
	`applicableCategories` json,
	`applicableServices` json,
	`minPurchase` decimal(10,2),
	`maxDiscount` decimal(10,2),
	`usageLimit` int,
	`validityType` enum('fixed_date','days_from_issue','no_expiry') DEFAULT 'days_from_issue',
	`validDays` int DEFAULT 30,
	`fixedStartDate` date,
	`fixedEndDate` date,
	`imageUrl` text,
	`backgroundColor` varchar(20) DEFAULT '#D4AF37',
	`textColor` varchar(20) DEFAULT '#0A1628',
	`isActive` boolean DEFAULT true,
	`isTransferable` boolean DEFAULT false,
	`totalIssued` int DEFAULT 0,
	`totalRedeemed` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `voucherTemplates_id` PRIMARY KEY(`id`)
);
