CREATE TABLE `voucherTransfers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`organizationId` int NOT NULL,
	`voucherInstanceId` int NOT NULL,
	`fromCustomerId` int NOT NULL,
	`fromCustomerName` varchar(100),
	`fromCustomerPhone` varchar(20),
	`toCustomerId` int,
	`toCustomerName` varchar(100),
	`toCustomerPhone` varchar(20) NOT NULL,
	`toCustomerEmail` varchar(320),
	`status` enum('pending','accepted','rejected','expired','cancelled') DEFAULT 'pending',
	`giftMessage` text,
	`claimCode` varchar(50) NOT NULL,
	`claimedAt` timestamp,
	`notificationSent` boolean DEFAULT false,
	`notificationChannel` enum('line','sms','email') DEFAULT 'line',
	`notificationSentAt` timestamp,
	`expiresAt` timestamp NOT NULL,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `voucherTransfers_id` PRIMARY KEY(`id`),
	CONSTRAINT `voucherTransfers_claimCode_unique` UNIQUE(`claimCode`)
);
