CREATE TABLE `cashDrawerRecords` (
	`id` int AUTO_INCREMENT NOT NULL,
	`settlementId` int NOT NULL,
	`organizationId` int NOT NULL,
	`operationType` enum('open','close','deposit','withdrawal','count') NOT NULL,
	`amount` decimal(12,2) NOT NULL,
	`balanceBefore` decimal(12,2),
	`balanceAfter` decimal(12,2),
	`operatedBy` int NOT NULL,
	`operatorName` varchar(255),
	`reason` text,
	`operatedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `cashDrawerRecords_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `dailySettlements` (
	`id` int AUTO_INCREMENT NOT NULL,
	`organizationId` int NOT NULL,
	`settlementDate` date NOT NULL,
	`openingCash` decimal(12,2) DEFAULT '0',
	`openedBy` int,
	`openedAt` timestamp,
	`closingCash` decimal(12,2),
	`closedBy` int,
	`closedAt` timestamp,
	`totalRevenue` decimal(12,2) DEFAULT '0',
	`cashRevenue` decimal(12,2) DEFAULT '0',
	`cardRevenue` decimal(12,2) DEFAULT '0',
	`linePayRevenue` decimal(12,2) DEFAULT '0',
	`otherRevenue` decimal(12,2) DEFAULT '0',
	`totalOrders` int DEFAULT 0,
	`completedOrders` int DEFAULT 0,
	`cancelledOrders` int DEFAULT 0,
	`refundedOrders` int DEFAULT 0,
	`totalAppointments` int DEFAULT 0,
	`completedAppointments` int DEFAULT 0,
	`noShowAppointments` int DEFAULT 0,
	`cashDifference` decimal(12,2) DEFAULT '0',
	`cashDifferenceNote` text,
	`status` enum('open','closed','reconciled') DEFAULT 'open',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `dailySettlements_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `lineChannelConfigs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`organizationId` int,
	`isPlatformLevel` boolean DEFAULT false,
	`channelId` varchar(100) NOT NULL,
	`channelSecret` text NOT NULL,
	`channelAccessToken` text NOT NULL,
	`liffId` varchar(100),
	`isActive` boolean DEFAULT true,
	`lastVerifiedAt` timestamp,
	`verificationStatus` enum('pending','verified','failed') DEFAULT 'pending',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `lineChannelConfigs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `paymentRecords` (
	`id` int AUTO_INCREMENT NOT NULL,
	`organizationId` int NOT NULL,
	`orderId` int,
	`appointmentId` int,
	`customerId` int,
	`paymentMethod` enum('cash','credit_card','debit_card','line_pay','transfer','other') NOT NULL,
	`amount` decimal(12,2) NOT NULL,
	`currency` varchar(10) DEFAULT 'TWD',
	`status` enum('pending','completed','failed','refunded','cancelled') DEFAULT 'pending',
	`transactionId` varchar(255),
	`referenceNumber` varchar(100),
	`paidAt` timestamp,
	`refundedAmount` decimal(12,2) DEFAULT '0',
	`refundedAt` timestamp,
	`refundReason` text,
	`processedBy` int,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `paymentRecords_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `settlementItems` (
	`id` int AUTO_INCREMENT NOT NULL,
	`settlementId` int NOT NULL,
	`orderId` int,
	`appointmentId` int,
	`itemType` enum('sale','refund','deposit','withdrawal','adjustment') NOT NULL,
	`paymentMethod` enum('cash','credit_card','debit_card','line_pay','transfer','other') NOT NULL,
	`amount` decimal(12,2) NOT NULL,
	`description` text,
	`customerId` int,
	`customerName` varchar(255),
	`staffId` int,
	`staffName` varchar(255),
	`transactionAt` timestamp NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `settlementItems_id` PRIMARY KEY(`id`)
);
