CREATE TABLE `autoSettlementSettings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`organizationId` int NOT NULL,
	`isEnabled` boolean DEFAULT false,
	`autoSettleTime` varchar(10) DEFAULT '23:00',
	`timezone` varchar(50) DEFAULT 'Asia/Taipei',
	`autoGenerateReport` boolean DEFAULT true,
	`reportRecipients` json,
	`reportFormat` enum('pdf','excel','both') DEFAULT 'pdf',
	`sendLineNotification` boolean DEFAULT false,
	`lineNotifyRecipients` json,
	`lastExecutedAt` timestamp,
	`lastExecutionStatus` enum('success','failed','skipped'),
	`lastExecutionError` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `autoSettlementSettings_id` PRIMARY KEY(`id`),
	CONSTRAINT `autoSettlementSettings_organizationId_unique` UNIQUE(`organizationId`)
);
--> statement-breakpoint
CREATE TABLE `revenueTrendSnapshots` (
	`id` int AUTO_INCREMENT NOT NULL,
	`organizationId` int NOT NULL,
	`snapshotDate` date NOT NULL,
	`periodType` enum('daily','weekly','monthly') DEFAULT 'daily',
	`totalRevenue` decimal(14,2) DEFAULT '0',
	`cashRevenue` decimal(14,2) DEFAULT '0',
	`cardRevenue` decimal(14,2) DEFAULT '0',
	`linePayRevenue` decimal(14,2) DEFAULT '0',
	`otherRevenue` decimal(14,2) DEFAULT '0',
	`totalOrders` int DEFAULT 0,
	`averageOrderValue` decimal(10,2) DEFAULT '0',
	`totalAppointments` int DEFAULT 0,
	`completedAppointments` int DEFAULT 0,
	`newCustomers` int DEFAULT 0,
	`returningCustomers` int DEFAULT 0,
	`hourlyRevenue` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `revenueTrendSnapshots_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `settlementReports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`organizationId` int NOT NULL,
	`settlementId` int,
	`reportType` enum('daily','weekly','monthly','custom') DEFAULT 'daily',
	`periodStart` date NOT NULL,
	`periodEnd` date NOT NULL,
	`title` varchar(255) NOT NULL,
	`reportData` json,
	`totalRevenue` decimal(14,2) DEFAULT '0',
	`cashRevenue` decimal(14,2) DEFAULT '0',
	`cardRevenue` decimal(14,2) DEFAULT '0',
	`linePayRevenue` decimal(14,2) DEFAULT '0',
	`otherRevenue` decimal(14,2) DEFAULT '0',
	`totalOrders` int DEFAULT 0,
	`averageOrderValue` decimal(10,2) DEFAULT '0',
	`totalAppointments` int DEFAULT 0,
	`completedAppointments` int DEFAULT 0,
	`pdfUrl` text,
	`excelUrl` text,
	`generatedBy` enum('auto','manual') DEFAULT 'manual',
	`generatedByUserId` int,
	`status` enum('generating','completed','failed') DEFAULT 'generating',
	`errorMessage` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `settlementReports_id` PRIMARY KEY(`id`)
);
