CREATE TABLE `importRecords` (
	`id` int AUTO_INCREMENT NOT NULL,
	`organizationId` int NOT NULL,
	`userId` int NOT NULL,
	`importType` enum('customer','product','staff','appointment','order') NOT NULL,
	`fileName` varchar(255) NOT NULL,
	`fileUrl` text,
	`totalRows` int DEFAULT 0,
	`successRows` int DEFAULT 0,
	`failedRows` int DEFAULT 0,
	`status` enum('pending','processing','completed','failed') DEFAULT 'pending',
	`errorLog` json,
	`startedAt` timestamp,
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `importRecords_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `lineChannelSettings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`organizationId` int NOT NULL,
	`channelId` varchar(100),
	`channelSecret` varchar(100),
	`channelAccessToken` text,
	`liffId` varchar(100),
	`webhookUrl` text,
	`isVerified` boolean DEFAULT false,
	`verifiedAt` timestamp,
	`botBasicId` varchar(100),
	`botDisplayName` varchar(255),
	`botPictureUrl` text,
	`richMenuId` varchar(100),
	`notificationEnabled` boolean DEFAULT true,
	`appointmentReminderEnabled` boolean DEFAULT true,
	`marketingMessageEnabled` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `lineChannelSettings_id` PRIMARY KEY(`id`),
	CONSTRAINT `lineChannelSettings_organizationId_unique` UNIQUE(`organizationId`)
);
--> statement-breakpoint
CREATE TABLE `organizationSubscriptions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`organizationId` int NOT NULL,
	`planId` int NOT NULL,
	`provider` enum('lemonsqueezy','stripe') DEFAULT 'lemonsqueezy',
	`externalSubscriptionId` varchar(255),
	`externalCustomerId` varchar(255),
	`status` enum('active','past_due','cancelled','paused','trialing') DEFAULT 'trialing',
	`currentPeriodStart` timestamp,
	`currentPeriodEnd` timestamp,
	`cancelAtPeriodEnd` boolean DEFAULT false,
	`cancelledAt` timestamp,
	`trialEndsAt` timestamp,
	`metadata` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `organizationSubscriptions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `paymentSettings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`organizationId` int NOT NULL,
	`provider` enum('lemonsqueezy','ecpay','stripe','linepay','jkopay') NOT NULL,
	`isEnabled` boolean DEFAULT false,
	`isTestMode` boolean DEFAULT true,
	`lsApiKey` text,
	`lsStoreId` varchar(100),
	`lsWebhookSecret` text,
	`ecpayMerchantId` varchar(50),
	`ecpayHashKey` varchar(100),
	`ecpayHashIv` varchar(100),
	`stripePublishableKey` text,
	`stripeSecretKey` text,
	`stripeWebhookSecret` text,
	`linePayChannelId` varchar(100),
	`linePayChannelSecret` text,
	`jkopayMerchantId` varchar(100),
	`jkopayApiKey` text,
	`defaultCurrency` varchar(10) DEFAULT 'TWD',
	`webhookUrl` text,
	`returnUrl` text,
	`cancelUrl` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `paymentSettings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `paymentTransactions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`organizationId` int NOT NULL,
	`orderId` int,
	`customerId` int,
	`provider` enum('lemonsqueezy','ecpay','stripe','linepay','jkopay','cash','transfer') NOT NULL,
	`transactionId` varchar(255),
	`externalTransactionId` varchar(255),
	`amount` decimal(12,2) NOT NULL,
	`currency` varchar(10) DEFAULT 'TWD',
	`status` enum('pending','processing','completed','failed','refunded','cancelled') DEFAULT 'pending',
	`paymentMethod` varchar(100),
	`cardLast4` varchar(4),
	`receiptUrl` text,
	`refundAmount` decimal(12,2),
	`refundReason` text,
	`refundedAt` timestamp,
	`metadata` json,
	`errorMessage` text,
	`paidAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `paymentTransactions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `subscriptionPlans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`provider` enum('lemonsqueezy','stripe') DEFAULT 'lemonsqueezy',
	`externalProductId` varchar(100),
	`externalVariantId` varchar(100),
	`price` decimal(10,2) NOT NULL,
	`currency` varchar(10) DEFAULT 'TWD',
	`billingInterval` enum('monthly','quarterly','yearly') DEFAULT 'monthly',
	`features` json,
	`maxUsers` int DEFAULT 5,
	`maxCustomers` int DEFAULT 500,
	`maxAppointments` int DEFAULT 1000,
	`isActive` boolean DEFAULT true,
	`sortOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `subscriptionPlans_id` PRIMARY KEY(`id`)
);
